baseURL: https://kolowy.fr/
languageCode: "en-us"
title: "Paul Dufour"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: Home
      name: Home
      title: Blog posts
      url: /#
      weight: 1
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 2
        # - identifier: gallery
        #  name: Gallery
        #  title: Blog posts
        #  url: /gallery
        #  weight: 3
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Paul Dufour"
  description: This is the personal website of Paul Dufour.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/avatar.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Paul Dufour" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Paul Dufour"
    subtitle: "Engineering studies at EPITA"
    content: "Engineering studies at EPITA. Computer Science enthusiast since I am 13 years old. I always want to discover new things"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/cv.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/kolowy
        - icon: fab fa-gitlab
          url: https://gitlab.com/kolowy
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/dufour-paul/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/moi.png"
    content: |-
      Engineering studies at EPITA. Computer Science enthusiast since I am 13 years old. I always want to discover new things. I have a strong interest in the intersection of technology.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "languages: C - C++ - C# - bash - Python - OCaml - ASM - Java"
        - "tools: vim - git - CI/CD - i3 - gdb - Docker - terraform - ansible - Nix"
        - "os: Linux (Arch Linux, Manjaro, Ubuntu) - Windows"
        - "frameworks: Vue.js - Nuxt.js - React"

  # Experience
  experience:
    enable: true
    title: "Internship"
    items:
      - job: "Assistant C Dièse Caml"
        company: "EPITA"
        date: "Sep 2023 - June 2024"
        content: |
          Assistant for first year EPITA students.
          - Writing of various practical exercises with C# exos
          - 3-hour TP session once a week with 40 students

      - job: "Developer Internship"
        company: "Vittascience"
        companyUrl: "https://fr.vittascience.com/"
        date: "Mai 2023 - August 2023"
        featuredLink:
          enable: true
          url: "https://fr.vittascience.com/python/?mode=mixed&console=bottom"
        content: >
          Creating a Python - Block translation
          Traduction of a Python Ast to [Blockly](https://developers.google.com/blockly) in Javascript

      - job: "Prologin"
        company: "Prologin"
        date: "Summer 2022"
        companyUrl: "https://prologin.org"
        featuredLink:
          enable: true
          name: "Prologin"
          url: "https://prologin.org"
        image: /images/prologin.png
        content: |
          - Help to develop new tools and maintain existing ones
          - Organization of Girls Can Code! workshop to promote woman integration in Computer Science
          - Met with high-ranking officials to promote / develop Prologin / Girls Can Code association and its actions


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
     - title: "Computer engineering"
       school: 
         name: "EPITA - Ecole Pour l’Informatique et les Techniques Avancées"
         url: "https://www.epita.fr/"
       date: "Sept 2021 - present"
       content: | 
         Third year of engineering studies at EPITA (Ecole Pour l’Informatique et les Techniques Avancées)

     - title: "Exchange semester - Thaïland"
       school:
         name: "Chulalongkorn University"
         url: https://www.chula.ac.th/en/
       date: "Jan 2023 - June 2023"
       content: "Exchange student at Information and Communication Engineering in Chulalongkorn University, 5 months"

     - title: "High School"
       school:
        name: "Marcq institution"
        url: "https://marcq-institution.com/"
       date: "Sep 2014 - Juin 2021"
       content: |
         High school in Marcq institution.
         Baccalorea in 2021

  organization:
    enable: true
    title: "Organization"
    subtitle: "Prologin"
    index: true 
    content: |
         Secretary of the association, I take care of new members and the association in general.
         I also manage part of Prologin infrastructure with ansible and terraform.
            - [Prologin Website](https://prologin.org)
            - [Girls Can Code! Website](https://girlscancode.fr)
    skills:
      enable: true
      title: |


        Here are a few technologies I've been working with recently:
      items:
        - Management of the association and registration of members.
        - Girls Can Code! workshop to promote the integration of women in Computer Science
        - Create a new website for Girls Can Code!
        - Met with high-ranking officials to promote and develop the association and its actions
        - Organization of a computer science contest where students under 21 have to solve problemsand challenges.
        - Maintaining the association’s infrastructure, develop new tools and maintain existing ones
        - Help in implementing a modern, code-compliant infrastructure with containerization of internal and external services.

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: HTTPD
        content: An http deamon server in C - 1 week
      - title: Hackathon
        content: Realization of an innovative project in team on the theme of the EAccessibility during 48 hours.
      - title: Unity Game Jam
        content: "Participation to the Unity First Game Jam : improvement of a game (1st place)"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: 42sh - EPITA Project
        content: >
          Creation of a POSIX Shell, group of 4 students
          Lexer, parser, exectution, and expansions
          Parser LL(2) with a reduce gramar of the scl
          Build with Autotools GNU
        image: /images/42sh.png
        badges:
           - "C"
           - "Autotools"
           - "GDB"
        links:
          - icon: fab fa-firefox
            url: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
      - title: Girls Can Code! website - Prologin organization
        content: |
          New website for Girls Can Code!, make with django and bootstrap
        image: /images/GCC.png
        featured:
          name: Link
          link: https://dev.girlscancode.fr
        badges:
           - "Django"
           - "Bootstrap"
        links:
          - icon: fab fa-firefox
            url: https://dev.girlscancode.fr
      - title: Optical Character Recognition Sudoku Solver - EPITA Project
        content: I have currently worked on a Optical Character Recognition with 3 friends for an EPITA project.
        image: /images/sudoku.png
        featured:
          name: Github
          link: https://github.com/sigma-Vision/Sigma-Vision
        badges:
           - "C"
           - "GDB"
           - "IA"
           - "Make"
        links:
          - icon: fab fa-firefox
            url: https://sigma-vision.github.io/doc-hugo/
          - icon: fab fa-github
            url: https://github.com/sigma-Vision/
      - title: "Battle Fields : Return of the Potatoes - VR Game - EPITA Project"
        content: "The game is a Tower Defense: potatoes will spawn in different places and will try to reach the player’s base. The players must prevent this and hold as long as possible."
        image: /images/battle.jpg
        featured:
          name: Finish
        badges:
           - "C#"
           - "Unity"
        links:
          - icon: fab fa-firefox
            url: https://github.com/laggron42/S2VRproject
          - icon: fab fa-github
            url: https://kolowy.github.io/S2VRweb/

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: paul.dufour@epita.fr
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/kolowy
      gitlab: https://gitlab.com/kolowy
      linkedin: https://www.linkedin.com/in/paul-dufour-560238237/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
