baseURL: https://kolowy.tk/

languageCode: "en-us"
title: "Paul Dufour"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
# googleAnalytics: 

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Paul Dufour"
  description: This is my personnal site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/avatar.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  # useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Paul Dufour."
    subtitle: "Engineering studies at EPITA"
    content: "Engineering studies at EPITA. Computer Science enthusiast since I am 13 years old. I always want to discover new things"
    image: /images/moi.png
    button:
      enable: true
      name: "Resume"
      url: /CV.png"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/kolowy
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/paul-dufour-560238237/
      customIcons:
        - icon: /images/prologin.png
          url: "https://prologin.org"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      Engineering studies at EPITA. Computer Science enthusiast since I am 13 years old. I always want to discover new things. I have a strong interest in the intersection of technology and art.
    skills:
      enable: true
      title: "Stuff I like :"
      items:
        - "languages : C, C#, OCaml, ASM 68000, bash"
        - "tools: git, vim, i3"
        - "os: Linux (Arch Linux, Manjaro, Ubuntu), Windows"
        - "containers: Docker"

  # Experience
  experience:
    enable: true
    title: "School career"
    items:
      - job: "Student"
        company: "EPITA"
        school: 
          name: "EPITA"
          url: "https://www.epita.fr/"
        date: "Sept 2021 - present"
        featuredLink:
          enable: true
          name: "EPITA"
          url: "https://www.epita.fr/"
        content: "Second year of engineering studies at EPITA"

      - job: "High School"
        company: "Marcq institution"
        companyUrl: "https://marcq-institution.com/"
        date: "Sep 2014 - Juin 2021"
        #featuredLink:
        #  enable: true
        #  url: "https://example.com"
        #info:
        #  enable: true
        #  content: I worked as a software developer for more than one year in Amazon.
        content: |
          High school in Marcq institution.
          Baccalorea in 2021
      
  # Education
  education:
    enable: true
    index: true
    title: "School Project"
    items:
      - title: "Optical Character Recognition Sudoku Solver"
        school: 
          name: "EPITA (Paris)"
          url: "https://www.epita.fr/"
        date: "Sept 2022 - present"
        featuredLink:
          enable: true
          name: "Sigma-Vision - OCR Sudoku Solver"
          url: "https://sigma-vision.github.io/doc-hugo/"
        content: I am currently working on a Optical Character Recognition with 3 friends for an EPITA project.
      
      - title: "Battle Fields: Return of the Potatoes - VR Game"
        school: 
          name: "EPITA (Paris)"
          url: "https://www.epita.fr/"
        date: "Jan 2022 - June 2022"
        featuredLink:
          enable: true
          name: "Battle Fields: Return of the Potatoes - VR Game"
          url: "https://kolowy.github.io/S2VRweb/"
        content: |
          The game is a Tower Defense: potatoes will spawn in different places and will try to reach the player’s base. The players must prevent this and hold as long as possible.
          Two players are required for this game :
          - The VR player, with a headset and controllers. He has a bow, on top of a tower, and has to aim and shoot the incoming enemies.
          - The PC player, with a mouse and a keyboard. He has a view from the top of the map and can purchase upgrades.
          Both players have to communicate together to survive through the endless waves of potatoes, wanting to steal all of our resources.
        
  
  association:
    enable: true
    title: "Associations"
    items:
      - job: "Prologin"
        company: "Prologin"
        date: "Mars 2022 - present"
        companyUrl: "https://prologin.org"
        featuredLink:
          enable: true
          name: "Prologin"
          url: "https://prologin.org"
        content: |
          I help prologin for :
          - organize the final
          - prepare the final
          - review the exercises of the contest

      - job: "Atelier"
        company: "Atelier"
        date: "Sept 2022 - present"
        companyUrl: "https://atelier.org"
        featuredLink:
          enable: false
        content: "Member of l'Atelier an EPITA association"
        
      - job: "Girls Can Code! (GCC)"
        company: "Prologin"
        date: "Sept 2022 - present"
        companyUrl: "https://atelier.org"
        featuredLink:
          enable: false
        content: "Member of l'Atelier an EPITA association"

      - job: "Girls Can Code! (GCC)"
        company: "Girls Can Code"
        date: "Mars 2022 - present"
        companyUrl: "https://girlscancode.fr"
        featuredLink:
          enable: true
          name: "Girls Can Code!"
          url: "https://girlscancode.fr"
        content: |
          I help Girls Can Code! (GCC)
          - make a static website
          - organize internships for girls
          - improve the content of the gcc courses
          - support for the development of the next GCC site


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google hash code
        content: Global team programming competition organized by Google.
        url: https://codingcompetitions.withgoogle.com/hashcode
      - title: Hackathon \#1 EPITA
        content: Realization of an innovative project in team on the theme of the EAccessibility during 48 hours.
      - title: Unity Game Jam
        content: "Participation to the Unity First Game Jam : improvement of a game (1st place)"


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Optical Character Recognition Sudoku Solver
        content: I am currently working on a Optical Character Recognition with 3 friends for an EPITA project.
        # image: /images/avatar.png
        featured:
          name: Demo
        badges:
           - "C"
           - "IA"
           - "OCR"
        links:
          - icon: fab fa-browser
            url: https://sigma-vision.github.io/doc-hugo/
          - icon: fab fa-github
            url: https://github.com/sigma-Vision/

      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/avatar.png
        featured:
          name: Demo
        badges:
           - "Hugo"
           - "Bootstrap"
           - "Javascript"
        links:
          - icon: fa fa-envelope
            url: paul.paul.dufour@gmail.com
          - icon: fab fa-github
            url: https://github.com/kolowy
          
      - title: "Battle Fields : Return of the Potatoes - VR Game"
        content: "The game is a Tower Defense: potatoes will spawn in different places and will try to reach the player’s base. The players must prevent this and hold as long as possible."
        image: /images/battle.jpg
        featured:
          name: Finish
        badges:
           - "C#"
           - "Unity"
        links:
          - icon: fa fa-browser
            url: https://github.com/laggron42/S2VRproject
          - icon: fab fa-github
            url: https://kolowy.github.io/S2VRweb/

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: paul.paul.dufour@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/kolowy
      linkedin: https://www.linkedin.com/in/paul-dufour-560238237/
      instagram: https://instagram.com/paul__dfr/
